In [14]:
import os
import pandas as pd #!pip install pandas

In [15]:
file_path =r'C:\Users\rud22\Desktop\MatchDriver'

In [16]:
file_path

'C:\\Users\\rud22\\Desktop\\MatchDriver'

In [17]:
files = [f for f in os.listdir(file_path) if f.lower().endswith('.xz')]

In [18]:
files

['courier_detailed_trajectory_20s.pkl.xz',
 'delivery_five_cities.pkl.xz',
 'pickup_five_cities.pkl.xz']

In [19]:
df_pickup = pd.read_pickle(os.path.join(file_path, files[2]))

In [20]:
df_pickup.dtypes

order_id             object
from_dipan_id        object
from_city_name       object
delivery_user_id     object
accept_time          object
book_start_time      object
expect_got_time      object
poi_lng             float64
poi_lat             float64
aoi_id               object
typecode             object
got_time             object
got_gps_time         object
got_gps_lng         float64
got_gps_lat         float64
accept_gps_time      object
accept_gps_lng      float64
accept_gps_lat      float64
ds                    int64
dtype: object

In [21]:
# order_id             주문아이디   
# from_dipan_id        주문자아이디 훈련데이터
# from_city_name       주문도시 훈련데이터
# delivery_user_id     운전자아이디 훈련데이터
# accept_time          배차 배정시간  훈련데이터
# book_start_time      배정시작시간 훈련데이터
# expect_got_time      픽업시간
# poi_lng              주문자위치정보 경도 훈련데이터
# poi_lat              주문자위치정보 위도 훈련데이터
# aoi_id               관심지역훈련데이터
# typecode             분류 훈련데이터
# got_time             픽업시간
# got_gps_time         픽업당시 차량 시간
# got_gps_lng          픽업위치정보 경도
# got_gps_lat          픽업위치정보 위도
# accept_gps_time      object 배차지정 차량시간
# accept_gps_lng      float64  배차지정 위치정보 경도 훈련데이터
# accept_gps_lat      float64  배차지정 위치정보 위도훈련데이터
# ds                    int64  날짜 구분

In [22]:
df_pickup.shape

(1123309, 19)

In [23]:
# pickup 데이터의  운전자수
len(df_pickup['delivery_user_id'].unique().tolist())

10484

In [24]:
df_pickup.head()

,order_id,from_dipan_id,from_city_name,delivery_user_id,accept_time,book_start_time,expect_got_time,poi_lng,poi_lat,aoi_id,typecode,got_time,got_gps_time,got_gps_lng,got_gps_lat,accept_gps_time,accept_gps_lng,accept_gps_lat,ds
0,a0b21cf88aa3958c059b4ed39a1a2e42,1dafc4452a67df23300d821948605ade,上海市,b9e8f1992e047964c749521c821d35e3,04-10 08:33:00,04-11 13:00:00,04-11 15:00:00,1.113996e+07,-6.482446e+06,5b4c12323e12ecd54fc201e90a825e8a,203ac3454d75e02ebb0a3c6f51d735e4,04-11 14:40:00,04-11 14:40:00,1.113996e+07,-6.482413e+06,NaN,NaN,NaN,411
1,9b2b2c3e4019596ff0219c2489b2ace8,0614b7ad98d39f7d05e5256bb704cf02,上海市,dc039d2c7f95b6f0ffc80f1ac0348fad,04-11 09:39:00,04-11 17:00:00,04-11 19:00:00,1.111619e+07,-6.510700e+06,9e32507b085d599e8fe887bc41b0130d,fe76dff35bb199cdb7329eba2b918f18,04-11 17:10:00,NaN,NaN,NaN,NaN,NaN,NaN,411
2,0aa0167409d543a8af0721b565f1e1b5,218285fb0849696616068eaf1bf42dc6,杭州市,efaa55e04dca7ed9d49c19a7ffc68284,04-11 08:26:00,04-11 11:00:00,04-11 13:00:00,1.100957e+07,-6.618438e+06,67610561d2fc6d552a5241b932103078,203ac3454d75e02ebb0a3c6f51d735e4,04-11 11:29:00,04-11 11:29:00,1.100953e+07,-6.618396e+06,NaN,NaN,NaN,411
3,059721c2af96ce982a4168a512bde352,2c74e744028ced6482eb767d0e708b7e,杭州市,c3029f297438e9b91866cfaaa0b2c68b,04-11 07:18:00,04-11 09:00:00,04-11 11:00:00,1.097015e+07,-6.632902e+06,66dd7cd801fdd9bcf8c5472db648805c,203ac3454d75e02ebb0a3c6f51d735e4,04-11 09:33:00,NaN,NaN,NaN,NaN,NaN,NaN,411
4,6536f09aaf82e64692c0dd193cc6cda7,165788e5c5ff91646e8da46bde41d318,重庆市,77c4c1d51c17eafbad619124a26f8979,04-11 14:37:00,04-11 15:00:00,04-11 17:00:00,9.477971e+06,-6.704148e+06,2f472cf5de4eaa83774dff7c41869615,203ac3454d75e02ebb0a3c6f51d735e4,04-11 15:14:00,NaN,NaN,NaN,NaN,NaN,NaN,411

In [25]:
#  운전자ID -> 운전자 name을 만들자
import random
from itertools import product

In [26]:
# 영어 성 200개

last_names = [
    "Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez",
    "Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin",
    "Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson",
    "Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores",
    "Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts",
    "Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes",
    "Stewart","Morris","Morales","Murphy","Cook","Rogers","Gutierrez","Ortiz","Morgan","Cooper",
    "Peterson","Bailey","Reed","Kelly","Howard","Ward","Cox","Richardson","Wood","Watson",
    "Brooks","Bennett","Gray","James","Hughes","Price","Myers","Long","Foster","Sanders",
    "Ross","Moreno","Perry","Powell","Russell","Jenkins","Patterson","Simmons","Fisher","Henderson",
    "Graham","Kim","Gonzales","Alexander","Ramos","Wallace","Griffin","West","Coleman","Hayes",
    "Chavez","Burke","Snyder","Hart","Shaw","Mendoza","Ford","Bryant","Douglas",
    "Fowler","Higgins","Hodges","Bishop","Meyer","Hanson","Johnston","Harper","Gordon","Mason",
    "Shannon","Cameron","Marshall","Wheeler","Williamson","Curtis","Dean","Oliver","Murray","Freeman",
    "Carlson","Chapman","Dixon","Horton","Hughes","Rice","Fernandez","Gomez","Payne","Bryant",
    "Arnold","Johns","Fleming","Hansen","Douglas","Burns","Gordon","Shaw","Holmes","Rice",
    "Robertson","Hunt","Black","Daniels","Palmer","Mills","Nichols","Grant","Knight","Ferguson",
    "Rose","Stone","Hawkins","Dunn","Perkins","Hudson","Spencer","Gardner","Stephens","Payne",
    "Pierce","Berry","Matthews","Arnold","Wagner","Willis","Ray","Watkins","Olson","Carroll",
    "Duncan","Snyder","Hart","Cunningham","Bradley","Lane","Andrews","Ruiz","Harper","Fox",
    "Riley","Armstrong","Carpenter","Weaver","Greene","Lawrence","Elliott","Chavez","Sims","Austin",
    "Peters","Kelley","Franklin","Lawson","Fields","Gutierrez","Ryan","Schmidt","Carr","Vasquez",
    "Castillo","Wheeler","Chapman","Oliver","Montgomery","Richards","Williamson","Johnston","Banks","Meyer"
]

In [27]:
first_names = [
    "James","Mary","John","Patricia","Robert","Jennifer","Michael","Linda","William","Elizabeth",
    "David","Barbara","Richard","Susan","Joseph","Jessica","Thomas","Sarah","Charles","Karen",
    "Christopher","Nancy","Daniel","Lisa","Matthew","Betty","Anthony","Margaret","Donald","Sandra",
    "Mark","Ashley","Paul","Kimberly","Steven","Emily","Andrew","Donna","Kenneth","Michelle",
    "George","Dorothy","Joshua","Carol","Kevin","Amanda","Brian","Melissa","Edward","Deborah",
    "Ronald","Stephanie","Timothy","Rebecca","Jason","Sharon","Jeffrey","Laura","Ryan","Cynthia",
    "Jacob","Kathleen","Gary","Amy","Nicholas","Shirley","Eric","Angela","Stephen","Helen",
    "Jonathan","Anna","Larry","Brenda","Justin","Pamela","Scott","Nicole","Brandon","Emma",
    "Benjamin","Samantha","Samuel","Katherine","Gregory","Christine","Frank","Debra","Alexander","Rachel",
    "Raymond","Catherine","Patrick","Carolyn","Jack","Janet","Dennis","Ruth","Jerry","Maria",
    "Tyler","Heather","Aaron","Diane","Jose","Virginia","Henry","Julie","Adam","Joyce",
    "Douglas","Victoria","Nathan","Olivia","Peter","Kelly","Zachary","Christina","Kyle","Lauren",
    "Walter","Joan","Harold","Evelyn","Jeremy","Judith","Ethan","Megan","Carl","Cheryl",
    "Keith","Andrea","Roger","Hannah","Gerald","Martha","Christian","Jacqueline","Terry","Frances",
    "Sean","Gloria","Arthur","Ann","Austin","Teresa","Noah","Kathryn","Lawrence","Sara",
    "Jesse","Janice","Joe","Jean","Bryan","Alice","Billy","Madison","Jordan","Doris",
    "Albert","Abigail","Dylan","Julia","Bruce","Judy","Willie","Grace","Gabriel","Denise",
    "Alan","Amber","Juan","Marilyn","Logan","Beverly","Wayne","Danielle","Ralph","Theresa",
    "Roy","Sophia","Eugene","Marie","Randy","Diana","Vincent","Brittany","Russell","Natalie",
    "Louis","Isabella","Philip","Charlotte","Bobby","Rose","Johnny","Alexis","Bradley","Kayla",
    "Billy","Lori","Clarence","Paula","Sean","Diana","Glenn","Annie","Dennis","Marie",
    "Shawn","Marilyn","Craig","Diana","Albert","Beverly","Randy","Catherine","Roy","Alice",
    "Wayne","Judith","Alan","Sara","Ernest","Jean","Jonathan","Kathy","Juan","Theresa",
    "Keith","Gloria","Christian","Jacqueline","Jesse","Martha","Henry","Victoria","Patrick","Carol"]

In [28]:
delivery_id = df_pickup['delivery_user_id'].unique().tolist()

In [29]:
# 이름과 성의 조합으로 전체 이름을 만듬
all_comb = [f"{ln} {fn}" for ln, fn in product(last_names, first_names)]

#랜덤하게 선택되게 하기위해
random.seed(42)
random.shuffle(all_comb)
# delivery_id 갯수만큼만 필요
names = (all_comb * (len(delivery_id) // len(all_comb) + 1))[:10484]
names

['Arnold Pamela',
 'Fox Jacob',
 'Watson Dorothy',
 'Martin Martha',
 'Hart Annie',
 'Black Martha',
 'Brown Joshua',
 'Riley Janice',
 'Palmer Douglas',
 'Chapman Randy',
 'Lawson Amanda',
 'Holmes Sean',
 'Lane Keith',
 'Arnold Billy',
 'Gutierrez Patrick',
 'Martin Henry',
 'Howard Eric',
 'Marshall Kyle',
 'Burns Ashley',
 'Armstrong Martha',
 'Chavez James',
 'Fernandez Matthew',
 'Powell Carol',
 'Gutierrez Megan',
 'Meyer Carol',
 'Perkins Kathy',
 'Horton Diana',
 'Brooks Roy',
 'Vasquez Kelly',
 'Harper Matthew',
 'Stewart Ruth',
 'Vasquez Brittany',
 'Arnold Zachary',
 'Perry Gerald',
 'Sanchez Jordan',
 'Bishop Katherine',
 'Johnston Shirley',
 'Myers Paula',
 'Hanson Martha',
 'Williamson Walter',
 'Phillips Matthew',
 'Hanson Brandon',
 'Moreno Marilyn',
 'Snyder Jennifer',
 'Moreno Helen',
 'Snyder Helen',
 'Davis Gloria',
 'Torres Cynthia',
 'Dunn Amy',
 'Hanson Diana',
 'Knight Brian',
 'Cruz Gabriel',
 'Perkins Patricia',
 'Hawkins Nicole',
 'Arnold Wayne',
 'Peterson Joshua',
 'Mendoza Sara',
 'Rice Christian',
 'Jackson Maria',
 'Rice Grace',
 'Olson Raymond',
 'Williamson Alice',
 'Franklin Joseph',
 'Fields Helen',
 'Baker Christian',
 'Horton Emma',
 'Armstrong Victoria',
 'Banks Kimberly',
 'Roberts Vincent',
 'Freeman Patrick',
 'Henderson Eugene',
 'Griffin Alexander',
 'Lawrence Rebecca',
 'Wheeler Charlotte',
 'Murray Thomas',
 'Cook Debra',
 'Diaz Michael',
 'Lawson Wayne',
 'Gonzalez Jesse',
 'Graham Kevin',
 'Fernandez Anthony',
 'Morales Kimberly',
 'Arnold Nicole',
 'Freeman Bruce',
 'Howard Paula',
 'Hernandez Teresa',
 'Hanson Johnny',
 'Shaw Danielle',
 'Ford Kimberly',
 'West Alexander',
 'Gomez Sandra',
 'Cunningham Jeffrey',
 'Miller Alice',
 'Hart Robert',
 'Elliott Sean',
 'Patterson Nicole',
 'Schmidt Tyler',
 'Douglas Andrea',
 'Cook Jesse',
 'West Judith',
 'Lane Roy',
 'Reyes Carol',
 'Lewis Wayne',
 'Garcia Ethan',
 'Burns Gabriel',
 'Lopez Walter',
 'Phillips Juan',
 'Douglas Ronald',
 'Nguyen Wayne',
 'White Marilyn',
 'Clark Beverly',
 'Castillo Keith',
 'Ferguson Steven',
 'Hanson James',
 'Perez Amy',
 'Martinez Jerry',
 'Long Beverly',
 'James Paul',
 'Murphy Jennifer',
 'Richardson Roger',
 'Gomez John',
 'Fox Kathryn',
 'Bryant Amy',
 'Cruz Martha',
 'Turner Gloria',
 'Oliver Henry',
 'Edwards David',
 'Stone Gerald',
 'Morales Ethan',
 'Mills Arthur',
 'Parker Alan',
 'Stewart Carol',
 'Fowler Andrew',
 'Shannon Willie',
 'Lawrence Dennis',
 'Ford Shawn',
 'Arnold Annie',
 'Higgins Deborah',
 'Cox Nathan',
 'Murray Sharon',
 'Roberts Russell',
 'Willis Alan',
 'Flores Nicole',
 'Williamson Louis',
 'Graham Stephanie',
 'Bishop Gary',
 'Bailey Rebecca',
 'Bryant Pamela',
 'Harper Judy',
 'Weaver Evelyn',
 'Peterson Alan',
 'Coleman Judith',
 'Bennett Betty',
 'Hudson Juan',
 'Curtis Roy',
 'Bryant Amy',
 'Perez Walter',
 'Scott Angela',
 'Murray Alan',
 'Chapman Theresa',
 'Hayes Joseph',
 'Hart Stephanie',
 'Rose Roy',
 'Wallace Judy',
 'Arnold Carol',
 'Burke Janet',
 'Gardner Russell',
 'Hunt Ethan',
 'Rose Joseph',
 'Lawrence Ralph',
 'Higgins Diana',
 'Martinez Barbara',
 'Thompson Kevin',
 'Knight Theresa',
 'Rice Jeremy',
 'Ward Russell',
 'Montgomery Jordan',
 'Douglas Diana',
 'Dean Evelyn',
 'Stone Albert',
 'Torres Karen',
 'Scott Betty',
 'Greene Albert',
 'Watson Sandra',
 'Dean Virginia',
 'Scott Brandon',
 'Moore Kyle',
 'Rodriguez Diana',
 'Marshall Scott',
 'Montgomery Michael',
 'Meyer Beverly',
 'Rodriguez Marilyn',
 'Marshall Pamela',
 'Coleman Sophia',
 'Sanchez Robert',
 'Cook Kathleen',
 'Richards Andrew',
 'Grant Angela',
 'Scott Clarence',
 'Weaver Tyler',
 'Moreno Beverly',
 'Pierce Martha',
 'Taylor Katherine',
 'Russell Kyle',
 'Grant Brandon',
 'Diaz Logan',
 'Nguyen Matthew',
 'Patterson Gloria',
 'Gonzalez Cynthia',
 'Hansen Edward',
 'Mitchell Cynthia',
 'Meyer Jeremy',
 'Miller Gloria',
 'Diaz Larry',
 'Morgan Nathan',
 'Wright Laura',
 'Vasquez Betty',
 'Fisher Benjamin',
 'Taylor Alice',
 'Meyer Isabella',
 'Davis Louis',
 'Burns Maria',
 'Shaw Kelly',
 'Myers Glenn',
 'Shaw Anthony',
 'Grant Harold',
 'Thomas Bradley',
 'Cruz Lauren',
 'Richardson Cheryl',
 'Davis Harold',
 'Roberts Kevin',
 'Nelson Jean',
 'Cunningham Gerald',
 'Harris Kenneth',
 'Reed Benjamin',
 'Perez Stephen',
 'Clark Keith',
 'Moore Bobby',
 'Jackson Terry',
 'Watson Sara',
 'Jenkins Barbara',
 'Hayes Gabriel',
 'Olson Evelyn',
 'Perry Jacqueline',
 'Roberts Dorothy',
 'Douglas Andrew',
 'Wood Kathryn',
 'Hayes Jacqueline',
 'Myers Jean',
 'Rice Shawn',
 'Taylor Louis',
 'Mendoza John',
 'Sims James',
 'King Laura',
 'Powell Lauren',
 'Johnston Martha',
 'Hodges Clarence',
 'Bailey Catherine',
 'Martinez Sarah',
 'Stewart Samuel',
 'Bryant Sara',
 'Bailey Walter',
 'Gray Gerald',
 'Mason Nathan',
 'Kim Douglas',
 'Snyder Shirley',
 'Cook Tyler',
 'Dunn Sharon',
 'Dunn Bobby',
 'Fields Ronald',
 'Gonzalez Nicole',
 'Murray Amy',
 'Clark Kathryn',
 'Gutierrez Lisa',
 'Thompson Frank',
 'Richards Sara',
 'Gonzalez Jacqueline',
 'Black Charlotte',
 'Wright Abigail',
 'Harris Matthew',
 'Mason Janice',
 'Harris Marie',
 'Howard Heather',
 'James Kyle',
 'Marshall Martha',
 'Ryan Aaron',
 'Ray Terry',
 'Curtis Ruth',
 'Hunt Lisa',
 'Martinez Theresa',
 'Matthews Susan',
 'Garcia Edward',
 'Higgins Bradley',
 'Gomez Willie',
 'Johnson Wayne',
 'White Julia',
 'Rodriguez Larry',
 'Ramirez Gary',
 'Rice George',
 'Stone Eric',
 'Hall Emily',
 'Lewis Willie',
 'Torres Angela',
 'Gomez Aaron',
 'Reyes Cynthia',
 'Richardson Sara',
 'Austin Jesse',
 'Campbell Ann',
 'Russell Michael',
 'Ward Arthur',
 'Cameron Sara',
 'Fowler Jacqueline',
 'Moreno Tyler',
 'Payne Megan',
 'Banks Christian',
 'Kim Olivia',
 'Fields Alexander',
 'Greene Kathleen',
 'Williamson Carolyn',
 'Nguyen Randy',
 'Payne Adam',
 'Dunn Karen',
 'Mendoza Joseph',
 'Campbell Hannah',
 'Gordon Adam',
 'Ford Harold',
 'Baker Rachel',
 'Phillips Charlotte',
 'Martin Diana',
 'Weaver Donald',
 'Nguyen Larry',
 'Wheeler Nicholas',
 'Shaw Donald',
 'Hart Natalie',
 'Johns Tyler',
 'Ferguson Juan',
 'Sims Robert',
 'Greene Carl',
 'Gardner Eugene',
 'Gonzalez John',
 'Smith Donald',
 'Curtis Paul',
 'Rice Carol',
 'Parker Rachel',
 'Sims Dylan',
 'Lopez James',
 'Franklin Zachary',
 'Fowler Brian',
 'Gordon Gloria',
 'Lopez Randy',
 'Baker Samantha',
 'Marshall Alexander',
 'Hanson Gregory',
 'Sims Brittany',
 'Brooks Catherine',
 'Matthews Kathryn',
 'Hernandez Sean',
 'Reyes Judith',
 'Riley Jordan',
 'Johnston Jonathan',
 'Perkins Keith',
 'Sanchez Martha',
 'Reyes Arthur',
 'Grant Douglas',
 'Gonzalez Alan',
 'Watson Brian',
 'Bennett Jordan',
 'Lee Donna',
 'Peters Kathleen',
 'Riley Virginia',
 'Peterson Noah',
 'Young Kimberly',
 'Russell Emily',
 'Fisher Shirley',
 'Elliott Angela',
 'Murphy Cynthia',
 'Jones Lauren',
 'Elliott Cheryl',
 'Chapman Ethan',
 'Reyes Doris',
 'Gomez Charles',
 'Moreno Sean',
 'Rice Tyler',
 'Simmons Nicholas',
 'Ortiz Stephen',
 'Dixon Debra',
 'Williamson Diana',
 'Martinez Martha',
 'Fernandez Jason',
 'Richards Julia',
 'Thomas Patrick',
 'Ortiz Michael',
 'Rice Bruce',
 'Johnston Amy',
 'Johnson Larry',
 'Greene Barbara',
 'Wagner Glenn',
 'Rodriguez George',
 'Henderson Steven',
 'Parker David',
 'Cox James',
 'Martinez Emma',
 'Chapman Christine',
 'Fernandez Keith',
 'Daniels Donald',
 'Howard David',
 'Stephens Juan',
 'Murphy Shirley',
 'Armstrong Patrick',
 'Cooper Jean',
 'Powell Keith',
 'Collins Samantha',
 'Gordon Emma',
 'Castillo Kyle',
 'Snyder Judith',
 'Austin Bradley',
 'Hernandez Nathan',
 'Ferguson Christopher',
 'Gordon Thomas',
 'Murray Christian',
 'Miller Andrew',
 'Jenkins Joe',
 'Watson Jessica',
 'Cunningham Randy',
 'Nichols Noah',
 'Torres Louis',
 'Fields Theresa',
 'Ford Lauren',
 'Watkins Gerald',
 'Roberts Brittany',
 'Watson Albert',
 'Schmidt Nancy',
 'Burns Karen',
 'Mitchell Frank',
 'Alexander Jessica',
 'King John',
 'Stephens Jacqueline',
 'Oliver Christine',
 'Flores Jessica',
 'Chavez Richard',
 'Hodges Jonathan',
 'Oliver Benjamin',
 'Baker Diana',
 'Dixon Diane',
 'Hughes Diana',
 'Palmer Virginia',
 'Collins Kevin',
 'Palmer Rose',
 'Taylor Theresa',
 'Hodges Ruth',
 'Long Sara',
 'West Amber',
 'Ross Gloria',
 'Morales Willie',
 'Williams Aaron',
 'Spencer Lawrence',
 'Mendoza Patricia',
 'Oliver Kathy',
 'Stewart Margaret',
 'Williamson George',
 'Jenkins Susan',
 'Moreno Matthew',
 'Reyes Sara',
 'Chapman Philip',
 'Kelley Amy',
 'Shaw Randy',
 'Burns Christian',
 'Riley Theresa',
 'Sanders Jean',
 'Cruz Sean',
 'Cunningham Frances',
 'Moreno Douglas',
 'Bradley Doris',
 'Andrews Larry',
 'Griffin Matthew',
 'Knight Ruth',
 'Fowler Julie',
 'Grant Jesse',
 'Burke Michelle',
 'Johns Mark',
 'Austin Donald',
 'Phillips Joshua',
 'Cruz Jacqueline',
 'Wheeler Daniel',
 'Bennett Diane',
 'Gordon Deborah',
 'Payne Joyce',
 'Baker Joshua',
 'Jenkins Harold',
 'Gomez Julia',
 'Bryant Isabella',
 'Jenkins Victoria',
 'Gordon Jennifer',
 'Shaw Amy',
 'James Shawn',
 'Kelley Scott',
 'Morales Annie',
 'Mason Judy',
 'Thompson Anna',
 'Mason Jonathan',
 'Campbell Juan',
 'Ford Ronald',
 'White Larry',
 'Graham Alan',
 'Bradley Jonathan',
 'Ray Christina',
 'White Marie',
 'Rice Randy',
 'Reed Charles',
 'Williamson Isabella',
 'Bishop Amy',
 'Nguyen Martha',
 'Hart Daniel',
 'Gutierrez Heather',
 'Chapman Alan',
 'Kim Adam',
 'Garcia Lori',
 'Jenkins Donna',
 'Parker Christine',
 'Fox Virginia',
 'Gonzalez Billy',
 'Payne Carol',
 'Morgan Douglas',
 'Johnson Nicole',
 'Ramirez Paula',
 'Lawson Victoria',
 'Gutierrez Diana',
 'Jones Alice',
 'Curtis Martha',
 'Johnston Maria',
 'Garcia Jeremy',
 'Payne Nicole',
 'Wilson Emma',
 'Hayes Henry',
 'Dixon Glenn',
 'Dunn Virginia',
 'Miller Julia',
 'Matthews Nicole',
 'Hart Larry',
 'King Roger',
 'Cook Ryan',
 'Morales Glenn',
 'Foster Logan',
 'Gutierrez Sharon',
 'Marshall Steven',
 'Hughes Angela',
 'Thomas Gloria',
 'Shannon Amber',
 'Cox Samantha',
 'Knight Marilyn',
 'Freeman Jennifer',
 'Chavez Cynthia',
 'Gray Angela',
 'Palmer Stephanie',
 'Jenkins Katherine',
 'Greene Gloria',
 'Nguyen Jacqueline',
 'Sims Jeremy',
 'Nichols Sean',
 'Walker Grace',
 'Palmer Jordan',
 'Phillips Jonathan',
 'Shannon Adam',
 'Chavez John',
 'Hawkins Brittany',
 'Robertson Arthur',
 'Hayes Marie',
 'Fields Wayne',
 'Robinson Philip',
 'Richardson Randy',
 'Snyder Gloria',
 'Gray Diana',
 'Nichols Wayne',
 'Hill Billy',
 'Perez Keith',
 'Ryan Dennis',
 'Howard Andrew',
 'Watson Edward',
 'Chavez Ethan',
 'Hall Hannah',
 'Young Albert',
 'Fields Jason',
 'Hughes Larry',
 'Shannon Henry',
 'Berry Amanda',
 'Fleming Noah',
 'Ward Kevin',
 'Watkins Patrick',
 'Price Bobby',
 'Gutierrez Margaret',
 'Spencer Gregory',
 'Oliver Mary',
 'Reyes Rose',
 'Bennett Patricia',
 'Snyder Theresa',
 'Hunt Evelyn',
 'Lopez Ethan',
 'Williamson Carl',
 'Coleman Lawrence',
 'Scott Keith',
 'Weaver Amy',
 'Lewis Samantha',
 'Bryant Roger',
 'Scott Christina',
 'Turner Linda',
 'Black Andrea',
 'Kelly Julia',
 'Hodges Marie',
 'Wheeler Joe',
 'Murray Beverly',
 'Rose Christopher',
 'Fisher Ralph',
 'Myers Shirley',
 'Bishop Tyler',
 'Hughes Billy',
 'Banks Annie',
 'Turner Megan',
 'Lopez Daniel',
 'Bailey Olivia',
 'Kim George',
 'Ray Joshua',
 'Cameron Christopher',
 'Henderson Grace',
 'Arnold Madison',
 'Perkins Timothy',
 'Hawkins Dorothy',
 'Ray Alan',
 'Bryant Melissa',
 'Myers Thomas',
 'Richards Dennis',
 'Young Albert',
 'Morgan Marie',
 'Ruiz Rose',
 'Gordon Kimberly',
 'Wagner Sarah',
 'Meyer Jacob',
 'Fowler Austin',
 'Berry Isabella',
 'Stewart Ryan',
 'Hayes Wayne',
 'Carroll Juan',
 'Fisher Zachary',
 'Gomez Deborah',
 'Baker Eric',
 'Ruiz Anthony',
 'Wright Kathy',
 'Phillips Tyler',
 'Scott Nicole',
 'Cook Christopher',
 'Adams Christine',
 'Hunt Mark',
 'Snyder Adam',
 'Peters Rebecca',
 'Fox Bradley',
 'Richards Craig',
 'Brown Jean',
 'Harper Kenneth',
 'Rose Andrea',
 'Jones Steven',
 'Shaw Sean',
 'Meyer Gloria',
 'Greene Nancy',
 'Wilson Ralph',
 'Hart Sara',
 'Williamson Glenn',
 'Ward Brenda',
 'Freeman Juan',
 'Nichols Logan',
 'Gutierrez Beverly',
 'Bennett Charles',
 'Knight Angela',
 'James Ryan',
 'Roberts Marilyn',
 'Jenkins Laura',
 'Evans Evelyn',
 'Perkins Samuel',
 'Montgomery Sean',
 'Kim Gerald',
 'Gardner Terry',
 'Douglas Sean',
 'Gonzales Jesse',
 'Carpenter Rose',
 'Bradley Scott',
 'Martin Ralph',
 'Reed Kathy',
 'Banks Lawrence',
 'Franklin Bobby',
 'Cooper Ernest',
 'Johnson Justin',
 'Greene Jacob',
 'Hill Marilyn',
 'Bryant Johnny',
 'Elliott Susan',
 'Thomas Rachel',
 'Wallace Jeremy',
 'Olson Frances',
 'Harper Karen',
 'Sanchez Alice',
 'Turner Marie',
 'Perry Annie',
 'Gonzales Janice',
 'Banks Patricia',
 'Taylor Benjamin',
 'Ruiz Lisa',
 'Higgins Harold',
 'Smith Stephanie',
 'Peters Timothy',
 'Thomas Steven',
 'Gomez Martha',
 'Perry Tyler',
 'Stone Diana',
 'Thomas Christina',
 'Chapman Jesse',
 'Bradley Noah',
 'Morales Brenda',
 'Dean Judith',
 'Dunn Thomas',
 'Vasquez Susan',
 'Marshall Harold',
 'Ramos Christopher',
 'Powell Danielle',
 'Murphy Juan',
 'Chavez Susan',
 'Lawson Noah',
 'Henderson Keith',
 'Watkins Lawrence',
 'Andrews Bobby',
 'Patterson Judith',
 'Bryant Paula',
 'Hall Clarence',
 'Cruz Joyce',
 'Ferguson Ryan',
 'Fowler Jordan',
 'Lane Roy',
 'Oliver Terry',
 'Chavez David',
 'Bryant Emma',
 'Ferguson Eric',
 'Fields Jeremy',
 'Morales Noah',
 'Snyder Glenn',
 'Ramos Betty',
 'Ruiz Amanda',
 'Cox Alexander',
 'Ramos Alan',
 'Payne Alan',
 'Sanders Larry',
 'Mendoza Janet',
 'West Alexis',
 'Lopez Sean',
 'James Gloria',
 'Hall Joshua',
 'Kim Tyler',
 'Gray Jonathan',
 'Cruz Teresa',
 'Hansen Matthew',
 'Wright Charles',
 'Horton Teresa',
 'White Joe',
 'Jackson Sophia',
 'Johnston Paul',
 'Vasquez Larry',
 'Adams Zachary',
 'Stephens Christopher',
 'Taylor Brian',
 'Smith Henry',
 'Lee Walter',
 'Long Jean',
 'Holmes Victoria',
 'Arnold Diana',
 'Hawkins Frank',
 'Mason Teresa',
 'Higgins Frank',
 'Payne Beverly',
 'Fowler Bryan',
 'Hanson Joe',
 'Hughes Pamela',
 'Elliott Michelle',
 'Brooks Thomas',
 'Duncan Douglas',
 'Ramos Kayla',
 'Austin Bruce',
 'Cunningham Shawn',
 'Martin Amy',
 'Burns Benjamin',
 'Lee Megan',
 'Rice Julia',
 'Ortiz Kimberly',
 'Murphy Ashley',
 'Reyes Jacqueline',
 'Ryan Dorothy',
 'Thompson Keith',
 'King Zachary',
 'Johnson Marie',
 'Martinez Jesse',
 'Wheeler Paula',
 'Williamson Diane',
 'Torres Stephen',
 'Peters George',
 'Perry Helen',
 'Hawkins Russell',
 'Foster Jonathan',
 'Gonzales Randy',
 'Nguyen Logan',
 'Reyes Christian',
 'Marshall Ashley',
 'Hughes Nicole',
 'Gordon Catherine',
 'Stephens Christian',
 'Mendoza Kathryn',
 'Bryant Jennifer',
 'Alexander Logan',
 'Reyes Tyler',
 'Carr Sean',
 'Wilson Jonathan',
 'Campbell Katherine',
 'Taylor Larry',
 'Armstrong Rose',
 'Brown Charlotte',
 'Nelson Gloria',
 'Palmer Amber',
 'Gonzalez Marilyn',
 'Mills Daniel',
 'Fowler William',
 'Schmidt George',
 'Alexander Nicholas',
 'Johnson Beverly',
 'Jenkins Jennifer',
 'Gonzalez Jose',
 'Alexander George',
 'Cunningham Natalie',
 'Perry Shirley',
 'Hall Eugene',
 'Andrews Denise',
 'Freeman Adam',
 'Palmer Keith',
 'Andrews Douglas',
 'Holmes Larry',
 'Rose Marilyn',
 'Daniels David',
 'Richards Marilyn',
 'Armstrong Marie',
 'Hanson Paula',
 'Perry Dennis',
 'Carr Evelyn',
 'Hughes Albert',
 'Oliver Danielle',
 'Spencer Hannah',
 'Lopez Pamela',
 'Bradley Beverly',
 'Gomez Betty',
 'Watkins Russell',
 'Rivera Judith',
 'Myers Henry',
 'Duncan David',
 'Wright Paula',
 'Bennett Randy',
 'Jackson Melissa',
 'Holmes Kayla',
 'King Abigail',
 'Collins Jesse',
 'Payne Frank',
 'Snyder Bruce',
 'Hawkins Paul',
 'Cox Martha',
 'Nguyen Sophia',
 'Hawkins Janet',
 'King Daniel',
 'Watson Brenda',
 'Payne Maria',
 'Higgins Henry',
 'Hansen Thomas',
 'Wood Angela',
 'Roberts Jack',
 'Williams Nicholas',
 'Brooks Keith',
 'Horton Jason',
 'Powell Justin',
 'Rivera Jerry',
 'Cook Randy',
 'Miller Stephen',
 'Murphy Judith',
 'Coleman Jacob',
 'Meyer Alexander',
 'Carlson Edward',
 'Pierce Thomas',
 'Carpenter Jesse',
 'Fowler Diane',
 'King Julia',
 'Knight Adam',
 'Alexander Annie',
 'Garcia Gabriel',
 'Roberts Carol',
 'Price Evelyn',
 'Lewis Richard',
 'Lawrence Janet',
 'Kim Vincent',
 'Oliver Larry',
 'Carr Victoria',
 'Wagner Jacqueline',
 'Black Ethan',
 'Perkins Dylan',
 'Peters Marilyn',
 'Robertson Isabella',
 'Ferguson Danielle',
 'Martinez John',
 'Gomez Michael',
 'Chapman Carolyn',
 'Banks Evelyn',
 'Reed Scott',
 'Adams Jacqueline',
 'Peterson Cynthia',
 'Gordon Angela',
 'Gordon Jeffrey',
 'Cruz Judith',
 'Ramirez Christian',
 'Wright Raymond',
 'Hart Alan',
 'Lawson Marie',
 'Allen Sara',
 'Turner Craig',
 'Gonzalez Theresa',
 'Watson Ernest',
 'Rodriguez Kathy',
 'Marshall Charlotte',
 'Hughes Amy',
 'Adams Clarence',
 'Gutierrez Helen',
 'Hill Frank',
 'Shaw Sandra',
 'Grant Tyler',
 'Cox George',
 'Oliver Billy',
 'Greene Roy',
 'Horton Stephanie',
 'Rose Jennifer',
 'Davis Rebecca',
 'Oliver Jose',
 'Meyer Sarah',
 'Green Shawn',
 'Bradley Charlotte',
 'Ward Natalie',
 'Ramirez Bobby',
 'Ward Kimberly',
 'Arnold Kyle',
 'Gonzales James',
 'Robertson Tyler',
 'Banks Brian',
 'Patterson Lauren',
 'Simmons Bryan',
 'Kelley Alice',
 'Thompson Carol',
 'Thomas Olivia',
 'Chapman James',
 'Evans Olivia',
 'Hayes Louis',
 'Gomez Steven',
 'Gordon Katherine',
 'Peterson Shawn',
 'Cox Gloria',
 'Chapman Jacqueline',
 'Oliver Ethan',
 'Sanders Douglas',
 'Banks Karen',
 'Campbell Bryan',
 'Shaw Juan',
 'Peterson Cheryl',
 'Torres Jesse',
 'Dixon Aaron',
 'Willis Bobby',
 'Mitchell Philip',
 'Armstrong Kelly',
 'Martinez Kevin',
 'Walker Sara',
 'Thompson Stephanie',
 'Miller Evelyn',
 'Dixon Christine',
 'Garcia Joshua',
 'Long Christina',
 'Holmes Michelle',
 'Clark Dennis',
 'Chapman Willie',
 'Chapman Laura',
 'Peterson Emily',
 'Patterson Gary',
 'Thompson Linda',
 'Fisher Nancy',
 'Fisher Victoria',
 'Hughes Olivia',
 'Hansen Johnny',
 'Weaver Frank',
 'Miller Jerry',
 'Oliver Olivia',
 'Wallace Christian',
 'Martin Glenn',
 'Smith Joseph',
 'Collins Cheryl',
 'Rodriguez Amanda',
 'Hernandez Christopher',
 'Armstrong James',
 ...]

In [30]:
# 기사 dataframe 생성
df_driver = pd.DataFrame({'delivery_user_id': delivery_id, 'delivery_user_name' : names})

In [31]:
df_driver.head()

                   delivery_user_id delivery_user_name
0  b9e8f1992e047964c749521c821d35e3      Arnold Pamela
1  dc039d2c7f95b6f0ffc80f1ac0348fad          Fox Jacob
2  efaa55e04dca7ed9d49c19a7ffc68284     Watson Dorothy
3  c3029f297438e9b91866cfaaa0b2c68b      Martin Martha
4  77c4c1d51c17eafbad619124a26f8979         Hart Annie

In [32]:
# 기존 데이터와 병합
df_pickup = df_pickup.merge(df_driver, on='delivery_user_id', how='left')

In [33]:
df_pickup.head()

,order_id,from_dipan_id,from_city_name,delivery_user_id,accept_time,book_start_time,expect_got_time,poi_lng,poi_lat,aoi_id,typecode,got_time,got_gps_time,got_gps_lng,got_gps_lat,accept_gps_time,accept_gps_lng,accept_gps_lat,ds,delivery_user_name
0,a0b21cf88aa3958c059b4ed39a1a2e42,1dafc4452a67df23300d821948605ade,上海市,b9e8f1992e047964c749521c821d35e3,04-10 08:33:00,04-11 13:00:00,04-11 15:00:00,1.113996e+07,-6.482446e+06,5b4c12323e12ecd54fc201e90a825e8a,203ac3454d75e02ebb0a3c6f51d735e4,04-11 14:40:00,04-11 14:40:00,1.113996e+07,-6.482413e+06,NaN,NaN,NaN,411,Arnold Pamela
1,9b2b2c3e4019596ff0219c2489b2ace8,0614b7ad98d39f7d05e5256bb704cf02,上海市,dc039d2c7f95b6f0ffc80f1ac0348fad,04-11 09:39:00,04-11 17:00:00,04-11 19:00:00,1.111619e+07,-6.510700e+06,9e32507b085d599e8fe887bc41b0130d,fe76dff35bb199cdb7329eba2b918f18,04-11 17:10:00,NaN,NaN,NaN,NaN,NaN,NaN,411,Fox Jacob
2,0aa0167409d543a8af0721b565f1e1b5,218285fb0849696616068eaf1bf42dc6,杭州市,efaa55e04dca7ed9d49c19a7ffc68284,04-11 08:26:00,04-11 11:00:00,04-11 13:00:00,1.100957e+07,-6.618438e+06,67610561d2fc6d552a5241b932103078,203ac3454d75e02ebb0a3c6f51d735e4,04-11 11:29:00,04-11 11:29:00,1.100953e+07,-6.618396e+06,NaN,NaN,NaN,411,Watson Dorothy
3,059721c2af96ce982a4168a512bde352,2c74e744028ced6482eb767d0e708b7e,杭州市,c3029f297438e9b91866cfaaa0b2c68b,04-11 07:18:00,04-11 09:00:00,04-11 11:00:00,1.097015e+07,-6.632902e+06,66dd7cd801fdd9bcf8c5472db648805c,203ac3454d75e02ebb0a3c6f51d735e4,04-11 09:33:00,NaN,NaN,NaN,NaN,NaN,NaN,411,Martin Martha
4,6536f09aaf82e64692c0dd193cc6cda7,165788e5c5ff91646e8da46bde41d318,重庆市,77c4c1d51c17eafbad619124a26f8979,04-11 14:37:00,04-11 15:00:00,04-11 17:00:00,9.477971e+06,-6.704148e+06,2f472cf5de4eaa83774dff7c41869615,203ac3454d75e02ebb0a3c6f51d735e4,04-11 15:14:00,NaN,NaN,NaN,NaN,NaN,NaN,411,Hart Annie

In [34]:
# 결손치 우리가 필요한 필드가 null인지 확인
null_counts = df_pickup.isnull().sum()
null_counts

order_id                    0
from_dipan_id               0
from_city_name              0
delivery_user_id            0
accept_time                 0
book_start_time             0
expect_got_time             0
poi_lng                     0
poi_lat                     0
aoi_id                      0
typecode                    0
got_time                    0
got_gps_time           980605
got_gps_lng            980605
got_gps_lat            980605
accept_gps_time       1099502
accept_gps_lng        1123309
accept_gps_lat        1123309
ds                          0
delivery_user_name          0
dtype: int64

In [35]:
# 중복값
duplicate_count = df_pickup.duplicated().sum()
print(f"{duplicate_count} 중복값 확인\n")
# 중복값 제거
df_pickup.drop_duplicates(inplace=True)

0 중복값 확인

In [36]:
# 필요한 컬럼으로 새로운 DataFrame 생성
pickup = df_pickup[['from_dipan_id', 'from_city_name', 'delivery_user_id', 'accept_time', 'book_start_time',  'poi_lng', 'poi_lat', 'aoi_id', 'typecode', 'ds', 'delivery_user_name']]

In [37]:
pickup.dtypes

from_dipan_id          object
from_city_name         object
delivery_user_id       object
accept_time            object
book_start_time        object
poi_lng               float64
poi_lat               float64
aoi_id                 object
typecode               object
ds                      int64
delivery_user_name     object
dtype: object

In [38]:
pickup.head()

,from_dipan_id,from_city_name,delivery_user_id,accept_time,book_start_time,poi_lng,poi_lat,aoi_id,typecode,ds,delivery_user_name
0,1dafc4452a67df23300d821948605ade,上海市,b9e8f1992e047964c749521c821d35e3,04-10 08:33:00,04-11 13:00:00,1.113996e+07,-6.482446e+06,5b4c12323e12ecd54fc201e90a825e8a,203ac3454d75e02ebb0a3c6f51d735e4,411,Arnold Pamela
1,0614b7ad98d39f7d05e5256bb704cf02,上海市,dc039d2c7f95b6f0ffc80f1ac0348fad,04-11 09:39:00,04-11 17:00:00,1.111619e+07,-6.510700e+06,9e32507b085d599e8fe887bc41b0130d,fe76dff35bb199cdb7329eba2b918f18,411,Fox Jacob
2,218285fb0849696616068eaf1bf42dc6,杭州市,efaa55e04dca7ed9d49c19a7ffc68284,04-11 08:26:00,04-11 11:00:00,1.100957e+07,-6.618438e+06,67610561d2fc6d552a5241b932103078,203ac3454d75e02ebb0a3c6f51d735e4,411,Watson Dorothy
3,2c74e744028ced6482eb767d0e708b7e,杭州市,c3029f297438e9b91866cfaaa0b2c68b,04-11 07:18:00,04-11 09:00:00,1.097015e+07,-6.632902e+06,66dd7cd801fdd9bcf8c5472db648805c,203ac3454d75e02ebb0a3c6f51d735e4,411,Martin Martha
4,165788e5c5ff91646e8da46bde41d318,重庆市,77c4c1d51c17eafbad619124a26f8979,04-11 14:37:00,04-11 15:00:00,9.477971e+06,-6.704148e+06,2f472cf5de4eaa83774dff7c41869615,203ac3454d75e02ebb0a3c6f51d735e4,411,Hart Annie

In [39]:
# 테이터를 분석하니 날짜형식이 잘못됨
pickup['accept_time'] = pd.to_datetime("2025-" + pickup["accept_time"].astype(str), format="%Y-%m-%d %H:%M:%S")
pickup['book_start_time'] = pd.to_datetime("2025-" + pickup["book_start_time"].astype(str), format="%Y-%m-%d %H:%M:%S")

C:\Users\rud22\AppData\Local\Temp\ipykernel_24628\2805611521.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pickup['accept_time'] = pd.to_datetime("2025-" + pickup["accept_time"].astype(str), format="%Y-%m-%d %H:%M:%S")
C:\Users\rud22\AppData\Local\Temp\ipykernel_24628\2805611521.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pickup['book_start_time'] = pd.to_datetime("2025-" + pickup["book_start_time"].astype(str), format="%Y-%m-%d %H:%M:%S")

In [40]:
pickup.dtypes

from_dipan_id                 object
from_city_name                object
delivery_user_id              object
accept_time           datetime64[ns]
book_start_time       datetime64[ns]
poi_lng                      float64
poi_lat                      float64
aoi_id                        object
typecode                      object
ds                             int64
delivery_user_name            object
dtype: object

In [41]:
#운행정보중에서 픽업데이터의 accept_time과 가장 근접한 차량위치정보 가져오기위해 
df_trajectory = pd.read_pickle(os.path.join(file_path, files[0]))

In [42]:
df_trajectory.shape

(51122257, 5)

In [43]:
df_trajectory.dtypes

ds              int64
postman_id     object
gps_time       object
lat           float64
lng           float64
dtype: object

In [44]:
#운행정보중에서 픽업데이터의 accept_time과 가장 근접한 차량위치정보 가져오기위해 
df_trajectory.head()

,ds,postman_id,gps_time,lat,lng
0,321,106f5ac22cfd1574b196d16fed62f90d,03-21 07:31:58,3.953700e+06,3.053400e+06
1,321,106f5ac22cfd1574b196d16fed62f90d,03-21 07:32:18,3.953700e+06,3.053398e+06
2,321,106f5ac22cfd1574b196d16fed62f90d,03-21 07:32:41,3.953700e+06,3.053398e+06
3,321,106f5ac22cfd1574b196d16fed62f90d,03-21 07:55:51,3.953700e+06,3.053398e+06
4,321,106f5ac22cfd1574b196d16fed62f90d,03-21 08:31:42,3.953929e+06,3.052367e+06

In [45]:
# 시간이 날짜와 시간밖에 없어서 년도 추가하고 자료형을 datatime변경
df_trajectory['gps_time'] = pd.to_datetime("2025-" + df_trajectory["gps_time"].astype(str), format="%Y-%m-%d %H:%M:%S")

In [46]:
df_trajectory.head()

,ds,postman_id,gps_time,lat,lng
0,321,106f5ac22cfd1574b196d16fed62f90d,2025-03-21 07:31:58,3.953700e+06,3.053400e+06
1,321,106f5ac22cfd1574b196d16fed62f90d,2025-03-21 07:32:18,3.953700e+06,3.053398e+06
2,321,106f5ac22cfd1574b196d16fed62f90d,2025-03-21 07:32:41,3.953700e+06,3.053398e+06
3,321,106f5ac22cfd1574b196d16fed62f90d,2025-03-21 07:55:51,3.953700e+06,3.053398e+06
4,321,106f5ac22cfd1574b196d16fed62f90d,2025-03-21 08:31:42,3.953929e+06,3.052367e+06

In [47]:
df_traj = df_trajectory.sort_values('gps_time')

In [48]:
df_pick = pickup.sort_values('accept_time')

In [49]:
df_traj = df_traj.sort_values('gps_time')

In [50]:
df_pick = df_pick.sort_values('accept_time')

In [51]:
df_traj = df_traj.rename(columns={'postman_id' : 'delivery_user_id'})

In [52]:
df_traj.dtypes

ds                           int64
delivery_user_id            object
gps_time            datetime64[ns]
lat                        float64
lng                        float64
dtype: object

In [53]:
pickup_with_driver = pd.merge_asof(
    df_pick,
    df_traj,
    left_on='accept_time',
    right_on='gps_time',
    by='delivery_user_id',  # 같은 운전자 기준
    direction='nearest'
)

In [54]:
pickup_with_driver.head()

,from_dipan_id,from_city_name,delivery_user_id,accept_time,book_start_time,poi_lng,poi_lat,aoi_id,typecode,ds_x,delivery_user_name,ds_y,gps_time,lat,lng
0,06dd115e8abc1ff2deb3c63d87cc3654,上海市,b10a57ad712c514e23d21af4592e5b64,2025-03-15 09:34:00,2025-03-21 17:00:00,1.115595e+07,-6.476487e+06,d7d6ac7cee0dd0a1af88fce564c6a70f,203ac3454d75e02ebb0a3c6f51d735e4,321,Morgan Thomas,321.0,2025-03-21 07:41:28,3.398393e+06,1.283685e+06
1,1890e710c27a3d84d34640a22ffe817a,上海市,e310641acb2a2124ec2756d5b1984edf,2025-03-15 09:39:00,2025-03-21 17:00:00,1.112961e+07,-6.465344e+06,af3862006941be90c43eed702955364d,203ac3454d75e02ebb0a3c6f51d735e4,321,Reed Brandon,NaN,NaT,NaN,NaN
2,3cdd6b7cfdef9021286ac836d8003a76,重庆市,2a2fa618a2acd87d32dc5e8f078d60cc,2025-03-15 09:42:00,2025-03-21 09:00:00,9.477415e+06,-6.685889e+06,11fbb27450b17b7faf5c29ec475c5acd,fe76dff35bb199cdb7329eba2b918f18,321,Reed Willie,321.0,2025-03-21 00:01:04,1.709404e+06,1.076709e+06
3,2c9b7acff227e2ca8e965dcb18c1d8c1,重庆市,024f1e816b504f904e5d0ab347ef6c82,2025-03-15 14:35:00,2025-03-22 17:00:00,9.453770e+06,-6.692354e+06,20b042a0681e39bf285f5954d37d6c36,203ac3454d75e02ebb0a3c6f51d735e4,322,Burke Brandon,322.0,2025-03-22 18:54:43,1.690740e+06,1.072244e+06
4,58b9d7b8b6e32cc8c4fa379b2ed3a0c0,烟台市,5e0774d7e49baa9e1be513565ff03bf9,2025-03-15 14:37:00,2025-03-21 17:00:00,1.113489e+07,-5.629769e+06,bef686227661b470e67333a41067592e,fe76dff35bb199cdb7329eba2b918f18,321,Oliver Billy,NaN,NaT,NaN,NaN

In [55]:
pickup_only = pickup_with_driver[pickup_with_driver['gps_time'].notnull()]

In [56]:
pickup_only.shape

(239618, 15)

In [57]:
# 결손치 우리가 필요한 필드가 null인지 확인
null_counts_1 = pickup_only.isnull().sum()
null_counts_1

from_dipan_id         0
from_city_name        0
delivery_user_id      0
accept_time           0
book_start_time       0
poi_lng               0
poi_lat               0
aoi_id                0
typecode              0
ds_x                  0
delivery_user_name    0
ds_y                  0
gps_time              0
lat                   0
lng                   0
dtype: int64

In [58]:
# 새로운데이터 속해있는 운전기사 목록
df_drive = pickup_only['delivery_user_id'].unique().tolist()

In [59]:
len(df_drive)

1136

In [60]:
# 중복값
duplicate_count = pickup_only.duplicated().sum()
print(f"{duplicate_count} 중복값 확인\n")
# 중복값 제거
pickup_only.drop_duplicates(inplace=True)

3 중복값 확인

C:\Users\rud22\AppData\Local\Temp\ipykernel_24628\1949305780.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pickup_only.drop_duplicates(inplace=True)

In [61]:
# 운전자정보
pickup_only.to_csv(os.path.join(file_path, 'pickup_only.csv'), index=False)